monolog:
  channels: ['api']
  handlers:
    file_log:
      type: stream
      path: "%kernel.project_dir%/log/%kernel.environment%/api.log"
      level: info
      channels: ['api']
#    sentry:
#      type: service
#      id: Sentry\Monolog\Handler