vich_uploader:
    db_driver: orm

    mappings:
       logo_equipe_world:
           uri_prefix: "%logo_world%"
           upload_destination: '%kernel.project_dir%/public%logo_world%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

